praiskup/resalloc

resalloc/helpers.py, resallocserver/config.py
Use safe_load instead of load, we don't need full.
Remove unused import.
=> Fixup yaml issues

resallocserver/api.py, resallocserver/manager.py
=> termination: don't request respin till transaction is committed

bin/resalloc, resalloc/client.py, resallocserver/api.py
This is useful to detect whether someone else asynchronously closed our
ticket.
=> client: set ticket.{closed,ready} after collect() call

bin/resalloc-server, resallocserver/config.py
=> Parse hostname from the config like it was intended

bin/resalloc-maint, resallocserver/maint.py
This allows us to easily print info about resources, e.g. data field
(= typically IP address, if we speak about VMs).
=> maint: add 'foreach-resource' command

.travis.yml
This is currently landing Rawhide.
=> travis: try to test against Python 3.10

bin/resalloc-maint, resallocserver/maint.py, resallocserver/models.py
=> Add resource-info command

bin/resalloc-maint, resallocserver/maint.py
=> Add --all and --unused options for resource-delete command

rpm/resalloc.spec.tpl
Complements: 58725658ef46f3ec4f70e920b5b11bd2f091c243
=> spec: wipe webui files for Python2

resalloc/client.py
Fixes: https://pagure.io/copr/copr/issue/2066
=> Catch xmlrpc error, it breaks builds in Copr

resallocwebui/app.py, rpm/resalloc.spec.tpl
Just a couple of changes for the Resalloc WebUI deployment
=> Resalloc WebUI deployment

resallocserver/models.py, resallocwebui/app.py, resallocwebui/templates/pools.html, resallocwebui/templates/resources.html
I am adding a new `/pools` page, and implementing the `/resources` page. Please see the commit descriptions for more info. Both the performance issues and the semantic issues that we were aware of, should be fixed now.
=> Resalloc WebUI improvements

MANIFEST.in, resallocwebui/cgi-resalloc, rpm/resalloc.spec.tpl
So it doesn't have to be duplicated in multiple ansible repositories
=> webui: add CGI script

resallocwebui/cgi-resalloc
=> webui: make the CGI script to be compatible with both lighttpd and apache

resallocwebui/app.py, resallocwebui/templates/home.html, resallocwebui/templates/layout.html, resallocwebui/templates/pools.html, resallocwebui/templates/resources.html
Adding a simple homepage and a layout template, so we don't have to duplicate the HTML code every time.
=> Webui homepage

resallocwebui/app.py, resallocwebui/templates/pools.html
=> webui: show max number of resources per pool

docs/release-new-version.md
Just a very short SOP on how to release a new resalloc version.
=> docs: describe how to release a new version

Makefile, NEWS, resallocserver/app.py, resallocserver/log.py, resallocserver/main.py, resallocserver/manager.py
see separate commits for details
=> Several fixes, logging and sqlalchemy pool fix

rpm/resalloc.spec.tpl
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
=> use spdx license

resallocserver/logic.py, resallocserver/manager.py
Fixes: https://github.com/fedora-copr/copr/issues/2490
=> manager: remove also taken resources that fail livecheck

rpm/resalloc.spec.tpl
=> spec: add missing dependencies for agent-spawner

rpm/resalloc.spec.tpl
=> agent-spawner: require updated get_redis_connection() method

rpm/resalloc.service
=> If PostgreSQL is available, make sure it is running

resallocwebui/templates/resources.html
The Data string may contain multiline-strings.  Use code formatting per: https://getbootstrap.com/docs/4.0/content/code/
=> web-ui: prap resource data into <pre>
