praiskup/resalloc

resalloc/client.py

On demand, when Connection is instantiated with
request_survives_server_restart=True (default=False).
Also fix several Pylint issues, and add docstrings.

client: request to survive server restart

---

MANIFEST.in
Makefile
buildrequirements.txt
resalloc/client.py
rpm/Makefile
rpm/resalloc.spec.tpl
setup.py
tests/__init__.py
tests/test_cli.py
unittests.sh

And while I'm on it, let's fix python2 problems and catch 'sock.error'
which works both on python2 and python3.  Add unittest for this code.

cli: retry for other errno numbers

---

Makefile
config/pools.yaml
pylintrc
resallocserver/config.py
resallocserver/logic.py
resallocserver/manager.py
shelltests/tests/basic.sh
shelltests/tests/check.sh
shelltests/tests/reuse.sh

(a) Provide RESALLOC_RESOURCE_DATA env var to checker.  This is useful
when e.g. checking for working AWS VMs -- to not re-translate the VM
name to PublicIP all the time (when the IP is in data).  This saves a
lot of API calls quota.
(b) Stop removing resources directly by Watcher thread, and let this
on Manager and garbage collector.  This simplifies code, and there's one
more race between Manager and Watcher.
(c) Never assign resources which nave non-zero Watcher fail counter.
(d) Document the RESALLOC_RESOURCE_DATA variable.

server: better checker thread logic

---

buildrequirements.txt
resallocserver/manager.py

Don't use top-level 'log' but 'self.log' from sub-threads.

manager: properly log from workers

---

resallocserver/manager.py
tests/test_command.py

This caused headaches in Fedora Copr recently because of the traceback
on "str + bytes" concatenation.  That concatenation was caused by
trimmed stdout, and stdout was flooded by ansible _error_?? output.
Our Ansible script choked on package installation because of
https://pagure.io/fedora-infrastructure/issue/9051

server: fix <trimmed> in AllocWorker stdout

---

config/pools.yaml

This config is there since the beginning of the project, but it wasn't
documented.

docs: document start_delay

---

resallocserver/alembic/versions/210774551cd3_performance_indexes.py
resallocserver/models.py

This sqlite_where is not supported by sqlalchemy 0.9.8 currently on EL7.
We should ideally port everything to python36 on EL7, but that is too
much work.  So for now, keep postgresql-only partial index, as those who
run against SQLite probably don't have that huge datasets anyway.

server: drop sqlite_where partial index

---

bin/resalloc-check-vm-ip
rpm/resalloc.spec.tpl
setup.py

This can be used as 'cmd_check' in case of the resource is a virtual
machine, and the DATA specified by 'cmd_new' denote an IP address.

New helper script 'resalloc-check-vm-ip'

---

.github/workflows/push-copr-build.yml

This is required to get the "merge" hash sent to Copr build.

ci: checkout in github actions

---

resallocserver/manager.py
resallocserver/models.py

This is still not foolproof but gives at least a little hint when
tickets are not being processed

Log when there are no resources or unusable ones

---

bin/resalloc-maint
resallocserver/maint.py

Fix #74 
It allows to `tail -f` logs for a given resource, e.g.
resalloc-maint resource-logs 123

Add command for printing logs

---

resallocserver/models.py

The STARTING resources doesn't have any data:
Traceback (most recent call last):
File "/usr/bin/resalloc-maint", line 114, in <module>
sys.exit(main())
File "/usr/bin/resalloc-maint", line 95, in main
maint.resource_info(args.resource)
File "/usr/lib/python3.10/site-packages/resallocserver/maint.py", line 64, in resource_info
print(json.dumps(resource.to_dict(), indent=4))
File "/usr/lib/python3.10/site-packages/resallocserver/models.py", line 103, in to_dict
result["data"] = result["data"].decode("utf8").strip()
AttributeError: 'NoneType' object has no attribute 'decode'

Fix resoure-info traceback for STARTING resources

---

resallocwebui/__init__.py
resallocwebui/app.py

In case we are working within the upstream project, we want to use static
files and templates from git (for easier development). Otherwise we want to
use files installed from the RPM package.

webui: if possible, use static files and templates from this directory

---

rpm/resalloc.spec.tpl

Adding an executable permissions and `httpd_sys_script_exec_t` context to the CGI script.
(I originally did that in ansible but that causes problems when reinstalling the package, and also would require extra configuration for different resalloc instances. The smart move is to do it in the package spec file)

A couple of WebUI deployment fixes

---

resallocserver/maint.py

To prevent tracebacks like this:
```
[resalloc@copr-be-dev ~][STG]$ resalloc-maint resource-info 113594
Traceback (most recent call last):
File "/usr/bin/resalloc-maint", line 114, in <module>
sys.exit(main())
File "/usr/bin/resalloc-maint", line 95, in main
maint.resource_info(args.resource)
File "/usr/lib/python3.10/site-packages/resallocserver/maint.py", line 64, in resource_info
print(json.dumps(resource.to_dict(), indent=4))
File "/usr/lib64/python3.10/json/__init__.py", line 238, in dumps
**kw).encode(obj)
File "/usr/lib64/python3.10/json/encoder.py", line 201, in encode
chunks = list(chunks)
File "/usr/lib64/python3.10/json/encoder.py", line 431, in _iterencode
yield from _iterencode_dict(o, _current_indent_level)
File "/usr/lib64/python3.10/json/encoder.py", line 405, in …
```

maint: fix resource-info for non-existing resource

---

README.md
rpm/resalloc.spec.tpl

I am converting the README to markdown, adding the list of known resalloc allocation scripts, and motivation for why to use the project.

Improve readme

---

Makefile
NEWS
README.md
config/pools.yaml
pylintrc
resallocserver/logic.py
resallocserver/manager.py
resallocserver/priority_queue.py
shelltests/testlib
shelltests/tests/ondemand.sh
tests/test_manager.py

Start resources on demand

---

resallocwebui/app.py

Fix https://github.com/fedora-copr/copr/issues/2882
Since we have on-demand resources, the `reload_config` now returns a tuple. See how it is used in `resallocserver.manager`.

webui: fix traceback from the pools page

---

rpm/resalloc.spec.tpl

While ATM the only package using resalloc-selinux is resalloc-webui, the reverse dependency doesn't make sense.  And in the future, the scope of the selinux module may increase.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2234812

rpm: don't require webui by selinux

---

.github/workflows/python-diff-lint.yml
bin/resalloc
config/agent-spawner/config.yaml
resalloc/client.py
resalloc_agent_spawner/dispatcher.py
resalloc_agent_spawner/helpers.py
resalloc_agent_spawner/worker.py
resallocserver/api.py
rpm/Makefile
rpm/resalloc-agent-spawner.service
rpm/resalloc.spec.tpl
setup.py

Agent Spawner daemon

---

resallocserver/manager.py

manager: don't allocate too many on-demand resources

---

resallocserver/manager.py

When a new on-demand pool is configured in pools.yaml, the cleanup logic is typically executed before a new resource is started there, and thus also before the database entry is created.
Fixes: #128

manager: fix "unknown resources cleanup" traceback

---

resalloc/client.py

Relates: https://github.com/fedora-copr/copr/pull/3113

survies_server_restart: ignore (verbosely) all socket errors

---

config/agent-spawner/config.yaml
resalloc_agent_spawner/worker.py

agent-spawner: base64 encode the resalloc ticket DATA in env

---

resallocserver/logic.py

Fix #141
sqlalchemy.exc.ArgumentError: Strings are not accepted for attribute
names in loader options; please use class-bound attributes directly.

Fix FTBFS in Fedora Rawhide

---

resalloc_agent_spawner/dispatcher.py
resalloc_agent_spawner/worker.py

The base64 encoding is worth doing on the dispatcher side, and store strings to Redis, instead of decoding and encoding it once more in worker (see #155).
Fixes: #155

agent-spawner: base64 encoding one more time

---

resallocserver/alembic/versions/b50e3f64fc2d_track_pool_max_value.py
resallocserver/manager.py
resallocserver/models.py
resallocwebui/app.py

The web-UI is typically driven by http server, without permissions to read /etc/resallocserver files or write /var/log/resallocserver.
Fixes: https://github.com/fedora-copr/copr/issues/3202

Do not load server configuration by web-UI

---

resallocserver/manager.py

This is a very poor hack, but we don't face exceptions too frequently here.  Let's restart if e.g. this happens:
Traceback (most recent call last):
File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
self.dialect.do_execute(
File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

server: ignore exceptions in the Watcher loop

---

NEWS
resallocserver/manager.py

CleanUnknownWorker: timeout one attempt after 120s
